# Generated by Django 6.0.8 on 2026-08-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='stage',
            field=models.CharField(choices=[('received', 'Recebida'), ('analyzing', 'Em análise'), ('awaiting_review', 'Aguardando revisão'), ('analysis_failed', 'Falha na análise'), ('resolved', 'Resolvida')], default='received', max_length=24),
        ),
        migrations.CreateModel(
            name='AnalysisAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=1000)),
                ('recommended_category', models.CharField(choices=[('access', 'Acesso'), ('billing', 'Cobrança'), ('technical_problem', 'Problema técnico'), ('feature_question', 'Dúvida sobre funcionalidade'), ('other', 'Outro')], max_length=32)),
                ('recommended_priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta')], max_length=16)),
                ('suggested_response', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_attempts', to='support_requests.supportrequest')),
            ],
        ),
    ]
