# Generated by Django 6.0.8 on 2026-08-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_requests', '0002_alter_supportrequest_stage_analysisattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisattempt',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisattempt',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisattempt',
            name='model',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='analysisattempt',
            name='outcome',
            field=models.CharField(choices=[('succeeded', 'Concluída'), ('failed', 'Falhou')], default='succeeded', max_length=16),
        ),
        migrations.AddField(
            model_name='analysisattempt',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisattempt',
            name='sanitized_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='analysisattempt',
            name='recommended_category',
            field=models.CharField(blank=True, choices=[('access', 'Acesso'), ('billing', 'Cobrança'), ('technical_problem', 'Problema técnico'), ('feature_question', 'Dúvida sobre funcionalidade'), ('other', 'Outro')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='analysisattempt',
            name='recommended_priority',
            field=models.CharField(blank=True, choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='analysisattempt',
            name='suggested_response',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='analysisattempt',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
