# Generated by Django 6.0.8 on 2026-08-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_requests', '0003_analysisattempt_duration_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='approved_response',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='final_category',
            field=models.CharField(blank=True, choices=[('access', 'Acesso'), ('billing', 'Cobrança'), ('technical_problem', 'Problema técnico'), ('feature_question', 'Dúvida sobre funcionalidade'), ('other', 'Outro')], max_length=32),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='final_priority',
            field=models.CharField(blank=True, choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta')], max_length=16),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='supportrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage', 'resolved'), _negated=True), models.Q(models.Q(('final_category', ''), _negated=True), models.Q(('final_priority', ''), _negated=True), models.Q(('approved_response', ''), _negated=True), ('resolved_at__isnull', False)), _connector='OR'), name='resolved_request_has_human_review'),
        ),
    ]
