# Generated by Django 6.0.8 on 2026-08-13 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_requests', '0004_supportrequest_approved_response_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisattempt',
            options={'ordering': ('created_at', 'pk')},
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em processamento'), ('completed', 'Concluído'), ('skipped', 'Ignorado')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_run', to='support_requests.analysisattempt')),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='support_requests.supportrequest')),
            ],
        ),
    ]
