# Generated by Django 6.0.8 on 2026-08-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_requests', '0005_alter_analysisattempt_options_analysisrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSubmissionBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('window_started_at', models.DateTimeField()),
                ('submission_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ip_hash', 'window_started_at'), name='unique_public_submission_bucket')],
            },
        ),
    ]
